component_depth: 3
languages:
- swift
# exclude:
# - /Pods/.*
# - /DirectoryYouWantToExclude/.*
# - .*/FileYouWantToExclude\.java
# - .*/SWRevealViewController\.h
# - .*/SWRevealViewController\.m
# - .*/GroupM8-Bridging-Header\.h
# - .*/DefaultType\.DefaultUnit
