component_depth: 3
languages:
- swift
- objectivec

- name: objectivec
  production:
    exclude:
        - .*/SWRevealViewController\.h
        - .*/SWRevealViewController\.m
        - .*/GroupM8-Bridging-Header\.h
        - /Pods/.*
